const {
  AndroidConfig,
  withAppBuildGradle,
  withGradleProperties,
} = require('expo/config-plugins');

const ABI_FILTERS_START = '// @generated by withAndroidArchitectures';
const ABI_FILTERS_END = '// @end generated by withAndroidArchitectures';

function withAbiFilters(config, buildArchs) {
  return withAppBuildGradle(config, (gradleConfig) => {
    const filters = buildArchs.map((arch) => `'${arch}'`).join(', ');
    const generatedBlock = [
      `        ${ABI_FILTERS_START}`,
      '        ndk {',
      `            abiFilters ${filters}`,
      '        }',
      `        ${ABI_FILTERS_END}`,
      '',
    ].join('\n');
    const existingBlock = new RegExp(
      `\\s*${ABI_FILTERS_START.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}[\\s\\S]*?${ABI_FILTERS_END.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}\\s*`,
      'g'
    );
    const withoutExistingBlock = gradleConfig.modResults.contents.replace(existingBlock, '\n');

    if (!withoutExistingBlock.includes('defaultConfig {')) {
      throw new Error('Android app build.gradle does not contain defaultConfig');
    }

    gradleConfig.modResults.contents = withoutExistingBlock.replace(
      '    defaultConfig {\n',
      `    defaultConfig {\n${generatedBlock}`
    );
    return gradleConfig;
  });
}

module.exports = function withAndroidArchitectures(config, options = {}) {
  const buildArchs = options.buildArchs || [];
  if (!Array.isArray(buildArchs) || buildArchs.length === 0) {
    throw new Error('buildArchs must contain at least one Android ABI');
  }

  const configWithArchitectures = withGradleProperties(config, (gradleConfig) => {
    gradleConfig.modResults = AndroidConfig.BuildProperties.updateAndroidBuildProperty(
      gradleConfig.modResults,
      'reactNativeArchitectures',
      buildArchs.join(',')
    );
    return gradleConfig;
  });

  return withAbiFilters(configWithArchitectures, buildArchs);
};
